name: Run bot check
on:
  pull_request:
    branches:
      - master

jobs:
  bot:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v2

      - name: Bot actions
        run: |
          echo run tests actions
          exit 1
